version: '3.7'
services:
  torch:
    container_name: torchsatsr-torch-rocm
    build:
      context: .
      dockerfile: Dockerfile
    image: torchsatsr/rocm:latest
    tty: true
    command: /bin/bash
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    volumes:
      - .:/src
    ports:
      - "8888:8888"
#      - "8265:8265"  # <- for ray (not working for now)
    shm_size: '16gb'
    group_add:
      - video
#    ipc: 'host'
    environment:
      - NB_USER=user
      - CHOWN_HOME=yes
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTERLAB_S3_ENDPOINT=http://s3:9000
      - JUPYTERLAB_S3_ACCESS_KEY_ID=minio
      - JUPYTERLAB_S3_SECRET_ACCESS_KEY=minio_taichi
      - JUPYTER_TOKEN=jupyter_taichi